ALTER TABLE games ADD COLUMN IF NOT EXISTS ending_reason VARCHAR(30);
ALTER TABLE games ADD COLUMN IF NOT EXISTS last_action_at TIMESTAMP;
ALTER TABLE games ADD COLUMN IF NOT EXISTS last_heartbeat_at TIMESTAMP;
ALTER TABLE game_results ADD COLUMN IF NOT EXISTS ending_reason VARCHAR(30);
